M48
; DRILL file {KiCad (6.0.6-0)} date Saturday, 01 April 2023 at 16:22:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-01T16:22:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X172.51Y-101.2
X178.29Y-101.2
T2
X214.1Y-79.438
X236.5Y-79.438
T0
M30
